AWSTemplateFormatVersion: "2010-09-09"
Description: Root test stack (SAFE TO DELETE)

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/network.yaml

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/security.yaml

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/s3.yaml

  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/alb.yaml
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnets: !GetAtt NetworkStack.Outputs.PublicSubnets

  ECSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ALBStack
    Properties:
      TemplateURL: stacks/ecs.yaml
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PrivateSubnets: !GetAtt NetworkStack.Outputs.PrivateSubnets
        AlbTargetGroup: !GetAtt ALBStack.Outputs.TargetGroupArn
