AWSTemplateFormatVersion: "2010-09-09"
Description: Application Load Balancer

Parameters:
  VpcId:
    Type: String
  PublicSubnets:
    Type: String

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !Ref PublicSubnets
      Scheme: internet-facing
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip

Outputs:
  TargetGroupArn:
    Value: !Ref TargetGroup
