name: Inject Exchange API Key

on:
  push:
    branches:
      - main  # Runs automatically on pushes to main branch

jobs:
  inject-key:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Inject EXCHANGE_API secret into currency.html
      - name: Inject API Key
        run: |
          echo "Injecting API key into /converter/currency.html"
          sed -i "s/\${EXCHANGE_API}/${{ secrets.EXCHANGE_API }}/g" converter/currency.html

      # Confirm injection
      - name: Confirm injection
        run: |
          grep "const API_KEY" converter/currency.html
