name: Daily ChatGPT Update

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 06:00 UTC
  workflow_dispatch:      # Allows manual trigger too

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install OpenAI SDK
        run: pip install openai

      - name: Run update script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python update.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Chatgpt.html
          git commit -m "Daily ChatGPT update" || echo "No changes to commit"
          git push
